### ISSUE TITLE
VScode with WSL not run?

### ISSUE THREAD

**Issue by worravut** [lukasbesch/laradock-bedrock#5]
### Info:
- Docker version (`$ docker --version`): Docker version 18.09.2, build 6247962
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux): Windows 10 Enterprise
- System info disto/version: 

### Issue:

_____

### Expected behavior:

_____./laradock.sh up

### Reproduce:

_____./laradock.sh: line 2: $'\r': command not found

### Relevant Code:

```
// place a code sample here
```

**Comment by lukasbesch** [comment]
Thank you for your report.
Looks like this is related to Windows line endings in the file.
I pulled in the upstream updates and converted the line endings to UNIX using `sed -i.bak 's/\r$//' laradock.sh`. Does this fix your issue?
